
//----------------------------------------------------
// The following code was generated by CUP v0.10j
// Tue Sep 30 15:01:35 CEST 2003
//----------------------------------------------------

package ufolib.convert;

/** CUP generated class containing symbol constants. */
public class BUSym {
  /* terminals */
  public static final int bbx = 14;
  public static final int encoding = 11;
  public static final int fontboundingbox = 5;
  public static final int startproperties = 7;
  public static final int endfont = 6;
  public static final int t_string = 18;
  public static final int t_number = 20;
  public static final int endproperties = 8;
  public static final int t_integer = 17;
  public static final int endchar = 16;
  public static final int EOF = 0;
  public static final int font = 3;
  public static final int size = 4;
  public static final int startfont = 2;
  public static final int chars = 9;
  public static final int error = 1;
  public static final int swidth = 12;
  public static final int t_iden = 19;
  public static final int dwidth = 13;
  public static final int startchar = 10;
  public static final int bitmap = 15;

  /* non terminals */
  static final int propertyentrys = 14;
  static final int propertyentry = 15;
  static final int bitmapsection = 24;
  static final int e_swidth = 21;
  static final int e_encoding = 20;
  static final int e_dwidth = 22;
  static final int hexlines = 26;
  static final int e_endfont = 11;
  static final int e_bitmap = 25;
  static final int properties = 4;
  static final int $START = 0;
  static final int e_fontboundingbox = 10;
  static final int e_startproperties = 12;
  static final int e_startfont = 7;
  static final int e_bbx = 23;
  static final int charmaps = 5;
  static final int e_font = 8;
  static final int e_endchar = 28;
  static final int e_size = 9;
  static final int charmap = 18;
  static final int hexline = 27;
  static final int e_chars = 16;
  static final int bdffile = 1;
  static final int e_startchar = 19;
  static final int charlist = 17;
  static final int header = 3;
  static final int starter = 2;
  static final int e_endproperties = 13;
  static final int ender = 6;
}

