/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PositionPopupMenu.java
 *
 * Created on 18 août 2010, 15:47:04
 */

package bt747.j2se_view.popupmenu;

import javax.swing.JPopupMenu;

/**
 *
 * @author mdeweerd
 */
public class PositionPopupMenu extends JPopupMenu {

    /**
	 * 
	 */
	private static final long serialVersionUID = -2055883175606795900L;
	/** Creates new form BeanForm */
    public PositionPopupMenu() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        miSetStart = new javax.swing.JMenuItem();
        miSetEnd = new javax.swing.JMenuItem();

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("bt747/j2se_view/Bundle"); // NOI18N
        miSetStart.setText(bundle.getString("PositionPopupMenu.miSetStart.text")); // NOI18N
        miSetStart.setToolTipText(bundle.getString("PositionPopupMenu.miSetStart.toolTipText")); // NOI18N
        miSetStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miSetStartActionPerformed(evt);
            }
        });
        add(miSetStart);

        miSetEnd.setText(bundle.getString("PositionPopupMenu.miSetEnd.text")); // NOI18N
        miSetEnd.setToolTipText(bundle.getString("PositionPopupMenu.miSetEnd.toolTipText")); // NOI18N
        miSetEnd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miSetEndActionPerformed(evt);
            }
        });
        add(miSetEnd);
    }// </editor-fold>//GEN-END:initComponents

    private void miSetStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miSetStartActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_miSetStartActionPerformed

    private void miSetEndActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miSetEndActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_miSetEndActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem miSetEnd;
    private javax.swing.JMenuItem miSetStart;
    // End of variables declaration//GEN-END:variables

}
